# Colors (Noctalia)

[colors.bright]
black = '#5a3f4d'
blue = '#ffa8c2'
cyan = '#ffe8f2'
green = '#ffd6e8'
magenta = '#ffccdd'
red = '#ffb8cc'
white = '#fff0f5'
yellow = '#ffe0f0'

[colors.cursor]
cursor = '#ffe0eb'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#ff8cb3'
cyan = '#ffd6e8'
green = '#ffccdd'
magenta = '#ffb3cc'
red = '#ff99b8'
white = '#ffe0eb'
yellow = '#ffcce0'

[colors.primary]
background = '#000000'
foreground = '#ffe0eb'

[colors.selection]
background = '#5a3f4d'
text = '#ffe0eb'
